// <auto-generated />
namespace GM.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class up9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(up9));
        
        string IMigrationMetadata.Id
        {
            get { return "201504071945461_up9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
